# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-SpamAssassin-Plugin-GoogleSafeBrowsing
version:      1.03
version_from: lib/Mail/SpamAssassin/Plugin/GoogleSafeBrowsing.pm
installdirs:  site
requires:
    base:                          0
    File::Spec:                    0
    Mail::SpamAssassin:            0
    Mail::SpamAssassin::Logger:    0
    Mail::SpamAssassin::Plugin:    0
    Net::Google::SafeBrowsing::Blocklist: 0
    Net::Google::SafeBrowsing::UpdateRequest: 0
    Test::More:                    0
    Test::Pod:                     0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
